#!/usr/bin/perl
# Last update 2003/8/11
BEGIN{
    $ENV{DRVDIR}="$ENV{HOME}/drivers" unless($ENV{DRVDIR});
    $ENV{DRVVAR}="$ENV{HOME}/var" unless($ENV{DRVVAR});
    push @INC,"$ENV{DRVDIR}/lib"; 
}
use SVR_dmy;

my $mode=$0;
$mode=~ s/.*\///;
$mode=~ s/d$//;
$sv=new SVR_dmy($mode);
$sv->server;
1;
