#!/bin/bash

[ "$1" ] || { echo Usage: run [daemon] ; exit ; }
which $1 &> /dev/null || { echo No such a command! ; exit ; }
RUNDIR="$HOME/var/run"
kill `cat $RUNDIR/$1.pid` &> /dev/null && echo Reloading $1
cd /
setsid $1 &> $RUNDIR/$1.err &
echo $! >$RUNDIR/$1.pid
